language: rust
rust:
  - stable
matrix:
  include:
    # Note: apt packages are the C cross compiler and the cross compiled C library
    - env: TARGET=aarch64-unknown-linux-gnu
      dist: trusty
      sudo: required
    - env: TARGET=arm-unknown-linux-gnueabi
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi
            - libc6-armel-cross
            - libc6-dev-armel-cross
    - env: TARGET=arm-unknown-linux-gnueabihf
      addons:
        apt:
          packages: &armhf
            - gcc-arm-linux-gnueabihf
            - libc6-armhf-cross
            - libc6-dev-armhf-cross
    - env: TARGET=armv7-unknown-linux-gnueabihf
      addons:
        apt:
          packages: *armhf
    - env: TARGET=i686-unknown-linux-musl
      addons:
        apt:
          packages: &i686
            - gcc-multilib
    - env: TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages: *i686
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-pc-windows-gnu
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - gcc-mingw-w64
    - env: TARGET=x86_64-apple-darwin
      os: osx
      sudo: required

install:
  - export OUTDIR=binaries
  - mkdir -p "$OUTDIR"
  - export PATH="$PATH:$HOME/.cargo/bin"
  - bash ci/install.sh
  - export PKG_CONFIG_ALLOW_CROSS=1

script:
  - bash ci/script.sh

deploy:
  provider: releases
  api_key:
    secure: 2ClmtkhNssFu9iwOceAuA2muchbqE3vou26EHtgqPlZwjHhLbxZJU7GUQPEyZOpOr3ao1a1kfIjDFTWUNDd+aHcV6Uf3VYbyXI3ijxqTZlJ51TlCXYCjZoIDrul7KnThpPLHLPdtlYUNp4Rq7e+tCajr+gkLDhdkNPXJmH+OVaXG2pYpm8DsNpt4X6LXj9cL70Zbazo1ATK60umz5BnF8jS4zAWAZy9F8ENUxJBSxmOuud/bB1UQ1LOWtRMR+EnnOaeJkJ4d25+f6MEAcTy4q/09dHYTa9h+kT7jN8IxBQv90UEjSgcJgxxwGA/qWc4dK0AIuKG5qOv0GJFvvJpYJSf/CpyjTrMggMFDwC0+qkTAmh8RLR3/tpVfkvLKcxNz0WAdD5Ee7dI7cQxVSypBL9CIZE5Y/lT9QRmlpAA591eBPFfy05HuvFYATgOwsPrjSpKdq7/MySTYXVNEQ5nKHv/gHOBkpdOpgfN3kRiIeUrEnpOOUjwAQjahUiosr5IzdxAjV0ocLaCkpell/Z84woZN0Kju/2LNfFLVsbHTGtnaGyY/D+3FXKV+ZM+y6cjOJuiLCvQX2tLTfdZKs0iQGsWE9bBUrk03Y8ZlfkSrcx0D+zjMPpFoAE+Mt210yuRrYUBmr78Wd124ioB1URu7U/1vGi0KkHYhTGT9fqnLYh4=
  file_glob: true
  file: binaries/*
  on:
    tags: true
    repo: jjacobson93/sec-gen

branches:
  only:
    - auto
    - master
