[package]
name = "sec-gen"
version = "1.0.0"
authors = ["Jeremy Jacobson <jjacobson93@gmail.com>"]

[dependencies]
base64 = "0.9.2"
clap = "2.32.0"
rand = "0.3"

[lib]
name = "secgen"
path = "src/lib.rs"

[[bin]]
name = "sec-gen"
path = "src/main.rs"
